# SPDX-FileCopyrightText: 2026 German Federal Office for Information Security (BSI) <https://www.bsi.bund.de>
# Software-Engineering: 2026 Intevation GmbH <https://intevation.de>
#
# SPDX-License-Identifier: Apache-2.0

name: Run Code Tests and Checks

on: [ push, pull_request ]

jobs:
  service-tests:
    name: "Test CLI Tool"
    runs-on: ubuntu-latest
    services:
      csaf-validator:
        image: ghcr.io/secvisogram/csaf-validator-service:latest
        ports:
          - 8082:8082

    steps:
    - uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: "3.14"

    - name: Install package
      run: pip install -e ".[dev]"

    - name: Run Tests with coverage
      run: pytest --cov=csaf_modifier
